language: python
python:
    - '3.3'
    - '3.4'
    - '3.5'

# commands to install dependencies
install:
    - python setup.py --quiet install

# commands to run tests
script:
    # Remove the outdated packages that Travis provides so it can install the
    # version of pytest that hangups requires.
    - pip uninstall --quiet --yes pytest py
    - python setup.py --quiet style
    - python setup.py --quiet lint
    - python setup.py --quiet test
    - pip install --quiet docutils
    - python setup.py check --metadata --restructuredtext --strict

# allow container-based infrastructure
sudo: false
